CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(180) NOT NULL UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS historial_usuarios (
  id INTEGER
    GENERATED ALWAYS AS IDENTITY
    PRIMARY KEY,

  usuario_id INTEGER
    NOT NULL
    REFERENCES usuarios(id)
    ON DELETE CASCADE,

  evento VARCHAR(120)
    NOT NULL,

  detalle TEXT,

  created_at TIMESTAMPTZ
    NOT NULL
    DEFAULT CURRENT_TIMESTAMP
);